remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Paul Nguyen"
description: "☕ Tech stories best served with a hot cup of coffee ☕"

# Build settings
markdown: kramdown
permalink: /posts/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
